theme: jekyll-theme-hacker
title: [Barber Lab]
description: [Studying quantitative bacterial physiology since 2025.]
logo: /profile_pic.JPG

social-network-links:
  email: "barber.527@osu.edu"
  github: felixbarber
  twitter: FelixBarber9
  linkedin: felix-barber
  
  # Select which social network share links to show in posts
share-links-active: 
  twitter: true
  linkedin: true
